---
- name: Add the OS specific variables
  include_vars: '{{ ansible_os_family }}.yml'
  tags: [ 'configuration', 'package', 'service', 'ntp' ]

- name: Install libselinux-python
  yum: name=libselinux-python state=installed
  when: ansible_os_family == 'RedHat'
  tags: [ 'package', 'libselinux-python' ]

- name: Install python-selinux
  zypper: name=python-selinux state=present
  when: ansible_os_family == 'Suse'
  tags: [ 'package', 'python-selinux' ]

- name: Install the required packages in CentOS derivatives
  yum: name=ntp state={{ ntp_pkg_state }}
  when: ansible_os_family == 'RedHat'
  tags: [ 'package', 'ntp' ]

- name: Install the required packages in Suse derivatives
  zypper: name=ntp state={{ ntp_pkg_state }}
  when: ansible_os_family == 'Suse'
  tags: [ 'package', 'ntp' ]

- name: Install the required packages in Debian derivatives
  apt: name=ntp state={{ ntp_pkg_state }} update_cache=yes cache_valid_time=86400
  when: ansible_os_family == 'Debian'
  tags: [ 'package', 'ntp' ]

- name: Copy the ntp.conf template file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
  - restart ntp
  tags: [ 'configuration', 'package', 'ntp' ]

- name: Start/stop ntp service
  service: name={{ ntp_service_name }} state={{ ntp_service_state }} enabled={{ ntp_service_enabled }} pattern='/ntpd'
  tags: [ 'service', 'ntp' ]
